import {
  beginStartupStepSnapshotValue,
  completeStartupStepSnapshotValue,
  createInitialStartupStepSnapshots,
  failStartupStepSnapshotValue,
  resetStartupStepSnapshotsValue,
} from 'src/stores/nostr/startupState';
import {
  buildAcceptedGroupInviteChatPlanValue,
  buildAvatarFallbackValue,
  buildGroupInviteRequestPlanValue,
  buildIdentifierFallbacksValue,
  buildUpdatedContactMetaValue,
  contactMetadataEqualValue,
  contactRelayListsEqualValue,
  findConflictingKnownGroupEpochNumberValue,
  findHigherKnownGroupEpochConflictValue,
  isContactListedInPrivateContactListValue,
  normalizeChatGroupEpochKeysValue,
  normalizeRelayStatusUrlsValue,
  normalizeWritableRelayUrlsValue,
  relayEntriesFromRelayListValue,
  resolveCurrentGroupChatEpochEntryValue,
  resolveGroupChatEpochEntriesValue,
  resolveGroupDisplayNameValue,
  resolveGroupPublishRelayUrlsValue,
  resolveIncomingChatInboxStateValue,
  resolvePrivateMessagesLiveReconnectSinceValue,
  shouldPreserveExistingGroupRelaysValue,
} from 'src/stores/nostr/valueUtils';

export const __nostrStoreTestUtils = {
  buildAcceptedGroupInviteChatPlan: buildAcceptedGroupInviteChatPlanValue,
  beginStartupStepSnapshot: beginStartupStepSnapshotValue,
  buildAvatarFallback: buildAvatarFallbackValue,
  buildIdentifierFallbacks: buildIdentifierFallbacksValue,
  buildUpdatedContactMeta: buildUpdatedContactMetaValue,
  buildGroupInviteRequestPlan: buildGroupInviteRequestPlanValue,
  completeStartupStepSnapshot: completeStartupStepSnapshotValue,
  contactMetadataEqual: contactMetadataEqualValue,
  contactRelayListsEqual: contactRelayListsEqualValue,
  createInitialStartupStepSnapshots,
  failStartupStepSnapshot: failStartupStepSnapshotValue,
  findConflictingKnownGroupEpochNumber: findConflictingKnownGroupEpochNumberValue,
  findHigherKnownGroupEpochConflict: findHigherKnownGroupEpochConflictValue,
  isContactListedInPrivateContactList: isContactListedInPrivateContactListValue,
  normalizeChatGroupEpochKeys: normalizeChatGroupEpochKeysValue,
  normalizeRelayStatusUrls: normalizeRelayStatusUrlsValue,
  normalizeWritableRelayUrls: normalizeWritableRelayUrlsValue,
  relayEntriesFromRelayList: relayEntriesFromRelayListValue,
  resetStartupStepSnapshots: resetStartupStepSnapshotsValue,
  resolveGroupDisplayName: resolveGroupDisplayNameValue,
  resolveGroupPublishRelayUrls: resolveGroupPublishRelayUrlsValue,
  resolveCurrentGroupChatEpochEntry: resolveCurrentGroupChatEpochEntryValue,
  resolveGroupChatEpochEntries: resolveGroupChatEpochEntriesValue,
  resolveIncomingChatInboxState: resolveIncomingChatInboxStateValue,
  resolvePrivateMessagesLiveReconnectSince: resolvePrivateMessagesLiveReconnectSinceValue,
  shouldPreserveExistingGroupRelays: shouldPreserveExistingGroupRelaysValue,
};
