services:
  relay:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - '7000:8080'
    volumes:
      - relay-data:/usr/src/app/db

  relay-two:
    image: scsibug/nostr-rs-relay:latest
    ports:
      - '7001:8080'
    volumes:
      - relay-two-data:/usr/src/app/db

volumes:
  relay-data:
  relay-two-data:
